### ISSUE TITLE
student2 not process if student1 failed

### ISSUE THREAD

**Issue by guillaume042** [vingerha/pronote2mqtt#16]
Hello,

Got two kids with two different ent.
I've noticed that if stutent1 failed (pronote not already activated for him) the application does not process stutent2.

Regards

**Comment by vingerha** [comment]
I recognise that issue, had the same with my kids too. 
I only made a temp solution but have not had time to fix it and test in full. 
If it is always the same kid then a temp solution could be to put the 'failing' one as secondary. 
Can you please also send me the error you see?

**Comment by guillaume042** [comment]
i will reproduce the previous issus this evening. 
Right now i got another.
Student1 is working
Student2 is not working (new ENT not yet released in pronotepy (only in master)).

```` 

pronote2mqtt              | 2023-09-06 13:17:17,940 INFO Parameters are ok !
pronote2mqtt              | 2023-09-06 13:17:17,940 INFO -----------------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:17,940 INFO #        Connexion to SQLite database                     #
pronote2mqtt              | 2023-09-06 13:17:17,940 INFO -----------------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:17,940 INFO Connexion to SQLite database...
pronote2mqtt              | 2023-09-06 13:17:17,941 INFO SQLite database connected !
pronote2mqtt              | 2023-09-06 13:17:17,942 INFO Last execution date 2023-09-06 13:16:12.435837, program was in version 0.4.0.
pronote2mqtt              | 2023-09-06 13:17:17,942 INFO Reinitialization of the database...
pronote2mqtt              | 2023-09-06 13:17:19,926 INFO Database reinitialized to version 0.2.0
pronote2mqtt              | 2023-09-06 13:17:19,926 INFO -----------------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:19,926 INFO #          Collection from Pronote                         #
pronote2mqtt              | 2023-09-06 13:17:19,926 INFO -----------------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:19,926 INFO Student 1-----------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:19,926 INFO INIT
pronote2mqtt              | 2023-09-06 13:17:19,927 DEBUG [ENT https://ent.iledefrance.fr/auth/login] Logging in with xxxx.xxxxx
pronote2mqtt              | 2023-09-06 13:17:21,017 INFO successfully logged in as xxxxxxx
pronote2mqtt              | 2023-09-06 13:17:21,048 INFO got onglets data.
pronote2mqtt              | 2023-09-06 13:17:21,048 INFO Collecting Student---------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:21,048 INFO Collecting Grades ---------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:21,488 INFO Collecting Averages---------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:21,909 INFO Collecting Periods---------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:21,909 INFO Skipping Averages---------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:21,909 INFO Collecting Absences---------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:22,344 INFO Collecting Lessons---------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:22,941 INFO Collecting Homework---------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:23,408 INFO Collecting Punishments---------------------------------------------------
pronote2mqtt              | 2023-09-06 13:17:23,963 INFO Student 2-----------------------------------------------------
pronote2mqtt              | Traceback (most recent call last):
pronote2mqtt              |   File "/app/pronote2mqtt.py", line 595, in <module>
pronote2mqtt              |     run(myParams)
pronote2mqtt              |   File "/app/pronote2mqtt.py", line 162, in run
pronote2mqtt              |     myPronote.getData(myParams.pronotePrefixUrl_2,myParams.pronoteUsername_2,myParams.pronotePassword_2,myParams.pronoteCas_2,myParams.pronoteGradesAverages_2,myParams.pronoteParent_2,myParams.pronoteFullName_2)
pronote2mqtt              |   File "/app/pronote.py", line 52, in getData
pronote2mqtt              |     _ent = getattr(ent, cas)
pronote2mqtt              | AttributeError: module 'pronotepy.ent.ent' has no attribute 'ent_ecollege78'
````
==> mqtt not updated even for student1.

Not a big deal for me i will just wait for the new release of pronotepy but maybe it is revelant for you.

**Comment by vingerha** [comment]
what you could do is go into the container and manually update to master, pip uninstall pronotepy and pip install pronotepy

**Comment by vingerha** [comment]
and… i have no issues yet as our school is slow with activating

**Comment by guillaume042** [comment]
> what you could do is go into the container and manually update to master, pip uninstall pronotepy and pip install pronotepy

Yeah but as the container is starting and restarting i can't launch bash :) and my competence are limited with docker.

trying that in docker-compose.yaml 
```
    command: ["bash", "/usr/bin/pip install -U git+https://github.com/bain3/pronotepy"]      
```
But 
```
pronote2mqtt              | Using '/app' as APP directory
pronote2mqtt              | bash: /usr/bin/pip install -U git+https://github.com/bain3/pronotepy: No such file or directory
````

**Comment by vingerha** [comment]
why is it restarting, odd, I do understand issues but that should not restart….normally. I myself use portainer to go to the prompt and now travelling so cannot help … tomorrow back

**Comment by guillaume042** [comment]
Release is out if you have some time :)

**Comment by vingerha** [comment]
which release? my new docker is of this morning and covers 12

**Comment by vingerha** [comment]
j;'ai vu 2.12.1...je vais voir aussi ajouter mon error-catching

**Comment by vingerha** [comment]
my docker creation runs wild...so 0.6.1 already has the 2.12.1 in it

**Comment by guillaume042** [comment]
> my docker creation runs wild...so 0.6.1 already has the 2.12.1 in it

sure ? 

```` 
 AttributeError: module 'pronotepy.ent.ent' has no attribute 'ent_ecollege78'
```` 
This new ENT had been introduced in 2.12.1

**Comment by vingerha** [comment]
Yes, sure
![image](https://github.com/vingerha/pronote2mqtt/assets/44190435/8e016bdc-63df-4d99-a815-7a97c138b0c8)

**Comment by guillaume042** [comment]
> Yes, sure ![image](https://user-images.githubusercontent.com/44190435/266080192-8e016bdc-63df-4d99-a815-7a97c138b0c8.png)

Got it:  Latest is not the latest tag 0.6.1 works

![image](https://github.com/vingerha/pronote2mqtt/assets/4631161/a0cd3c73-8578-4719-bb39-df38d91f2f5b)

**Comment by vingerha** [comment]
yeah, I need to repair my docker-create flow, it kicks off with every change

**Comment by vingerha** [comment]
I think to have fixed the student 1/2 issue in 'latest'  release. also fixed some stuff for punishments, please test when you have the time

**Comment by vingerha** [comment]
Fixed, will still have to improve on error handling
